version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root directory of package.json
    schedule:
      interval: "daily" # Can be daily, weekly, or monthly
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
