version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 10 
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    groups:
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
