// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
// https://www.storyblok.com/faq/how-can-i-utilize-typescript-in-my-storyblok-project
import type { ISbStoryData } from "storyblok";
export type MultilinkStoryblok =
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      anchor?: string;
      rel?: string;
      title?: string;
      prep?: string;
      linktype: "story";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: unknown;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: unknown;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: unknown[];
        default_full_slug?: null | string;
        translated_slugs?: null | unknown[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "url";
      rel?: string;
      title?: string;
      [k: string]: unknown;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      email?: string;
      linktype: "email";
      [k: string]: unknown;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "asset";
      [k: string]: unknown;
    };

export interface ButtonStoryblok {
  label?: string;
  link?: Exclude<
    MultilinkStoryblok,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  variant?: number | string;
  size?: number | string;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface GridStoryblok {
  columns?: (
    | ButtonStoryblok
    | FeatureStoryblok
    | GridStoryblok
    | HeroSectionStoryblok
    | PageStoryblok
    | PostPageStoryblok
    | TeaserStoryblok
  )[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface AssetStoryblok {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: unknown;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: unknown;
}

export interface HeroSectionStoryblok {
  headline?: string;
  subheadline?: string;
  buttons?: ButtonStoryblok[];
  image?: AssetStoryblok;
  fullWidth?: number | string;
  component: "hero-section";
  _uid: string;
  [k: string]: unknown;
}

export interface PageStoryblok {
  body?: (
    | ButtonStoryblok
    | FeatureStoryblok
    | GridStoryblok
    | HeroSectionStoryblok
    | PageStoryblok
    | PostPageStoryblok
    | TeaserStoryblok
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: unknown;
  text?: string;
  [k: string]: unknown;
}

export interface PostPageStoryblok {
  image?: AssetStoryblok;
  title?: string;
  text?: RichtextStoryblok;
  component: "post page";
  _uid: string;
  [k: string]: unknown;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}
